### PR TITLE
WIP - Autotools build

### PR DESCRIPTION
**Pull request by menzel-r**
The `configure.ac` needs some work, but here is a first-attempt autotools build.

### CODE REVIEW

**Comment by menzel-r** [comment]
@underwoo @thomas-robinson 
Please take a look when you have a minute and let me know if this is something you are interested in pursuing.

**Comment by thomas-robinson** [comment]
@edwardhartnett had attempted something like this with AM4.  Now that our code is slowly making its way out to the public, this might be a good place to develop the autotools build.

The other thing to keep in mind is that this isn't a mirror of the internal development of atmos_phys.

**Comment by edwardhartnett** [comment]
I have a tool which, starting with a mkmf fortran project, creates the confgure.ac and all the Makefile.am files for a project. It's a little python script that does the heavy lifting of generating an autotools build for a GFDL project. Would you like me to run it on this code and present the resutl as a pull request?

**Comment by thomas-robinson** [comment]
@edwardhartnett that would be helpful.  Thank you.

**Pull request closed without merging**
